global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tecos-api-monitor'

scrape_configs:
  - job_name: 'tecos-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.25.0.1:8081']
        labels:
          application: 'tecos-api'
          environment: 'development'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          service: 'postgresql'
